<a href="https://colab.research.google.com/github/yyhhhhhh/python/blob/main/3_18.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
cars = ['bmw','audi','toyota']
cars.sort()
print(cars)

cars = ['bmw','audi','toyota']
cars.sort(reverse = True)
print(cars)

['audi', 'bmw', 'toyota']
['toyota', 'bmw', 'audi']


In [6]:
locations = ['西藏','新疆','四川','南极','冰岛']
print(locations,type(locations))
for i in range(len(locations)):
  print(locations[i])

['西藏', '新疆', '四川', '南极', '冰岛'] <class 'list'>
西藏
新疆
四川
南极
冰岛


In [7]:
numbers = list(range(1,10,2))
print(numbers)

[1, 3, 5, 7, 9]


In [10]:
squares = []
for i in range(1,10):
  squares.append(i ** 2)
print(squares)

[1, 4, 9, 16, 25, 36, 49, 64, 81]


In [11]:
squares = [value ** 2 for value in range(1,10)]
print(squares)

[1, 4, 9, 16, 25, 36, 49, 64, 81]


In [12]:
for i in range(1,21):
  print(i)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20


In [13]:
arr = []
for i in range(1,11):
  arr.append(i ** 3)
print(arr)

[1, 8, 27, 64, 125, 216, 343, 512, 729, 1000]


In [22]:
colors = ['red','green','blue','yellow','white','black']
print(colors[0:])
print(colors[1:])
print(colors[:-1])
print(colors[1:4])
print(colors[-5:-2])
print(colors[::-1])
print(colors[3::-2])
print(colors[1:-4:-1])

['red', 'green', 'blue', 'yellow', 'white', 'black']
['green', 'blue', 'yellow', 'white', 'black']
['red', 'green', 'blue', 'yellow', 'white']
['green', 'blue', 'yellow']
['green', 'blue', 'yellow']
['black', 'white', 'yellow', 'blue', 'green', 'red']
['yellow', 'green']
[]


In [24]:
a = [list(range(10*i,10*i+6)) for i in range((6))]
print(a)
print(a[0][3:5])
print(a[4:][4:])
print(a[:][2])
print(a[2::2][2::2])

[[0, 1, 2, 3, 4, 5], [10, 11, 12, 13, 14, 15], [20, 21, 22, 23, 24, 25], [30, 31, 32, 33, 34, 35], [40, 41, 42, 43, 44, 45], [50, 51, 52, 53, 54, 55]]
[3, 4]
[]
[20, 21, 22, 23, 24, 25]
[]


In [26]:
import numpy as np
a = [list(range(10*i,10*i+6)) for i in range((6))]
b = np.array(a)
print(b[0,3:5])
print(b[4:,4:])
print(b[:,2])
print(b[2::2,2::2])

[3 4]
[[44 45]
 [54 55]]
[ 2 12 22 32 42 52]
[[22 24]
 [42 44]]


In [32]:
food = ['apple','noodle','meat','rice']
fine_food = food[:]
print(food[0:2])
print(food[1:3])
print(food[-2:])
food.append('pear')
print(food)
fine_food.append('orange')
print(fine_food)

['apple', 'noodle']
['noodle', 'meat']
['meat', 'rice']
['apple', 'noodle', 'meat', 'rice', 'pear']
['apple', 'noodle', 'meat', 'rice', 'orange']


In [36]:
print('以下是元组的基本操作')
tup1 = ()
tup1 = ('Google','Runoob',1997,2000)
tup2 = tuple(range(10))
tup2 = (1,2,3,4,5,6,7)
print(tup1)
print(tup2)
print(tup1[0])
print(tup2[1:5])
print(tup2 * 2)
print(1 in tup2)
print(len(tup2))
print(tup1 + (26.8,0))
print(tup1[::2])

以下是元组的基本操作
('Google', 'Runoob', 1997, 2000)
(1, 2, 3, 4, 5, 6, 7)
Google
(2, 3, 4, 5)
(1, 2, 3, 4, 5, 6, 7, 1, 2, 3, 4, 5, 6, 7)
True
7
('Google', 'Runoob', 1997, 2000, 26.8, 0)
('Google', 1997)


In [42]:
student = {}
student = dict()
student = {
    'no' : '210501110123',
    'name' : '杨宇航',
    'age' : 21,
    'course' : ['数学','英语','java']
}
print(student)
print(student['no'])
print(student.get('class'))
print(student.keys())
print(student.values())
print(student.items())
print('age' in student)
print('sex' in student)

{'no': '210501110123', 'name': '杨宇航', 'age': 21, 'course': ['数学', '英语', 'java']}
210501110123
None
dict_keys(['no', 'name', 'age', 'course'])
dict_values(['210501110123', '杨宇航', 21, ['数学', '英语', 'java']])
dict_items([('no', '210501110123'), ('name', '杨宇航'), ('age', 21), ('course', ['数学', '英语', 'java'])])
True
False


In [50]:
student = {
    'no' : '210501110123',
    'name' : '杨宇航',
    'age' : 21,
    'course' : ['数学','英语','java']
}
student['age'] = 22
student['job'] = 'Dev'
del student['job']
for k,v in student.items():
  print(k,'---',v)
print()
for k in student.keys():
  print(k)
print()
for k in sorted(student.keys()):
  print(k)

no --- 210501110123
name --- 杨宇航
age --- 22
course --- ['数学', '英语', 'java']

no
name
age
course

age
course
name
no


In [52]:
a,b = set('abc'),set('dabc')
a = {x for x in 'abracadabra' if x not in 'abc'}
print(a,b)

{'d', 'r'} {'d', 'a', 'b', 'c'}


In [59]:
a = set([1,2,3,4,5])
b = set([2,4,6,8,10])
print(a)
print(b)
a.add('e')
print(a)
a.remove(1)
print(a)
c = a.pop()
print(a)
a.clear()
print(a)

{1, 2, 3, 4, 5}
{2, 4, 6, 8, 10}
{1, 2, 3, 4, 5, 'e'}
{2, 3, 4, 5, 'e'}
{3, 4, 5, 'e'}
set()


In [64]:
a = set([1,2,3,4,5])
b = set([2,4,6,8,10])
print('并集')
print(a | b)
print(a.union(b))
print('交集')
print(a & b)
print(a.intersection(b))
print('差集')
print(b-a)
print(a.difference(b))
print('异或')
print(a^b)
print(a.symmetric_difference(b))

并集
{1, 2, 3, 4, 5, 6, 8, 10}
{1, 2, 3, 4, 5, 6, 8, 10}
交集
{2, 4}
{2, 4}
差集
{8, 10, 6}
{1, 3, 5}
异或
{1, 3, 5, 6, 8, 10}
{1, 3, 5, 6, 8, 10}
